### ISSUE TITLE
PS1 Setting is overridden by Bashrc

### ISSUE THREAD

**Issue by Checkroth** [shimizukawa/sshh#4]
# Details

- Environment: Ubuntu 18.04
- Shell command: `/bin/bash`

Default .bashrc file on Ubuntu contains a PS1 setting, which will override the PS1 environment variable set in `sshh/main.py`

This can by fixed by creating a temporary rc file which first loads .bashrc, and then sets the environment variable.

Implemented at #3

**Comment by shimizukawa** [comment]
#3 has been merged. Thanks!
